apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: clientelle-image
  namespace: pipelines-tutorial
spec:
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/clientelle:latest
  type: image
