---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    jkube.io/git-url: https://github.com/mmartofel/clientelle.git
    app.openshift.io/vcs-uri: https://github.com/mmartofel/clientelle.git
    jkube.io/git-commit: fe331f0c4d67b1443606761b8cebf5d868f04322
    jkube.io/git-branch: master
    jkube.io/scm-url: https://github.com/spring-projects/spring-boot/clientelle
    jkube.io/scm-tag: HEAD
  labels:
    app: clientelle
    provider: jkube
    version: 0.0.1-SNAPSHOT
    group: pl.bik
  name: clientelle
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: clientelle
