---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: clientelle
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: clientelle@sha256:2bc73bd169424503f3c3e624011a8588f396e90aa51d9770ad75de92e1e69d1f
        namespace: pipelines-tutorial
      name: latest
